jwt.secret=${JWT_SECRET}
spring.application.name=aprendendo-spring

spring.datasource.url=jdbc:postgresql://localhost:5432/aprendendo_spring
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.jpa.open-in-view=false